stages:
  - build
  - deploy

build:
  stage: build
  only:
    - master
  script:
    - docker build -t qiushaocloud/ub2204-min-desktop-x11vnc:latest .
  tags:
    - qiushaocloud-runner

deploy:
  stage: deploy
  only:
    - master
  script:
    - docker login --username $DOCKER_HUB_USER_NAME --password $DOCKER_HUB_USER_PASSWORD
    - docker push qiushaocloud/ub2204-min-desktop-x11vnc:latest
  tags:
    - qiushaocloud-runner
