version: "3"
services:
  qiushaocloud-ub2204-min-desktop-x11vnc:
    image: qiushaocloud/ub2204-min-desktop-x11vnc
    container_name: qiushaocloud-ub2204-min-desktop-x11vnc
    hostname: qiushaocloud-ub2204-min-desktop-x11vnc
    ports:
      - "$VNC_PORT:5900"
    environment:
      - "SCREEN_WIDTH:$SCREEN_WIDTH"
      - "SCREEN_HEIGHT:$SCREEN_HEIGHT"
      - "VNC_PASSWORD:$VNC_PASSWORD"